### ISSUE TITLE
怎么画曲线

### ISSUE THREAD

**Issue by rich2300** [BIT-TYJ/SLOOP#2]
您好，我想使用analyze-benchmark.py绘制一下P-R曲线，报如下错：frames_vertexs未定义，请问这个帧顶点怎么定义呀？请问注释部分的代码是什么意思呀

**Comment by harold-lu-bit** [comment]
您好，我们更新了代码，在新的代码中要画曲线需要先运行`SLOOP.py`生成结果，在项目文件夹根目录/log中可以找到该结果，将生成的文件名填写到`analyze-benchmark.py`顶部的LOG_FILE_NAME中应该就可以画图了。注释掉的代码应该是之前留下的不相关的代码，画图应该不需要用到。

**Comment by rich2300** [comment]
好滴，非常感谢！
