### ISSUE TITLE
问题请教

### ISSUE THREAD

**Issue by rich2300** [BIT-TYJ/SLOOP#3]
您好，我用您提供的数据集运行并生成pkl文件，为什么保存下来的文件比您提供的pkl文件大很多，而且ICP的误差达到几十米呢？

**Comment by harold-lu-bit** [comment]
您好，感谢您对我们工作的关注！
我们之前上传的数据有误，现在已经重新上传了文件（也即是SemanticKITTI的原始数据），同时也修改了代码的部分路径变量。重新下载数据并拉取代码应该可以获得正确的结果。

**Comment by rich2300** [comment]
非常感谢您的耐心回复，我利用新下载的文件重新尝试生成.pkl文件，并将结果使用plot_icp_result.py画出来，所得结果和原来差别不大呢，如下所示： 
![Uploading 2024-10-14 11-44-31屏幕截图.png…]()
yaw_error  yaw_error_raw  inlier_ratio  inlier_num
7  86.598602      86.598386      0.999973      185128

**Comment by rich2300** [comment]
不好意思是我的问题，已经解决，不用回复啦，给你造成的困惑我深表抱歉！

**Comment by harold-lu-bit** [comment]
好的哈，那我关闭这个issue了
