### ISSUE TITLE
代码疑问

### ISSUE THREAD

**Issue by rich2300** [BIT-TYJ/SLOOP#4]
您好，请问在执行icp配准的时候，给的源点云和目标点云分别是pc1和pc2，这两个怎么得到的呢？都用的kitti07吗

**Comment by BIT-TYJ** [comment]
是的，两帧做icp配准用的对应帧的点云。

**Comment by rich2300** [comment]
好滴好滴，感谢您的耐心回复呜呜呜，我还想请教一下# 显示语义实例点云 use_vis_inst_cloud这个参数设置为True之后怎么不显示点云呀？怎么才能显示这个语义点云呢？

**Comment by harold-lu-bit** [comment]
可视化在之前调试的时候被注释掉了，要再打开的话把`sk2semantic_array.py`的第130行的注释取消就好

**Comment by rich2300** [comment]
好滴好滴，万分感谢，那pairs_kitti下的相关文件是怎么生成的呀？这个文件夹下存储的是相应帧的配对关系吗？因为我想用semantickitti里面的其他序列做下测试~可以分享一下生成neg文件的相关代码嘛

**Comment by BIT-TYJ** [comment]
pairs_kitti来自一个benchmark ssc：https://github.com/lilin-hitcrt/SSC   ，存储的是相应帧的配对关系。

**Comment by rich2300** [comment]
好滴好滴 感谢感谢~使用他们给的：
### Pair Lists
[Lists of evaluation samples](https://drive.google.com/file/d/1Y540LJFZHiaAooUX2KtxNIQhw-kzy7gQ/view?usp=sharing). We select all positive samples, and randomly select some negative samples according to a fixed ratio for evaluation. This folder contains lists of evaluation samples we used for the KITTI dataset (pairs_kitti) and KITTI-360 dataset (pairs_kitti360). The naming rule of the parent folder of the lists is "neg_ratio". For example, "neg_10" means that the number of negative samples is ten times that of positive samples.
这里面的数据吗，这个谷歌云盘失效了，可以分享一下吗呜呜呜，希望这是最后一次打扰您呜呜呜

**Comment by rich2300** [comment]
不用啦 我找到他们老版本的代码 里面有提供~

**Comment by BIT-TYJ** [comment]
好的好的，那我关闭这个issue啦
